// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SeleniumTest.Features.BicycleClaimsForm
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("BicycleClaimsForm WhatHasHappened")]
    public partial class BicycleClaimsFormWhatHasHappenedFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "WhatHasHappened.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "BicycleClaimsForm WhatHasHappened", "\tIn order to verify that the 1st section works properly\r\n\tI want to change values" +
                    " for all section 1 elements\r\n\tAnd check if the fields are filled properly", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("click radio button and verify")]
        [NUnit.Framework.TestCaseAttribute("1st checkbox", "Bicycle or parts of it have been stolen", "Bicycle has been vandalized", "Bicycle has got broken", "Bicycle has been damaged in a collision with a motor vehicle", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2nd checkbox", "Bicycle has been vandalized", "Bicycle or parts of it have been stolen", "Bicycle has got broken", "Bicycle has been damaged in a collision with a motor vehicle", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3rd checkbox", "Bicycle has got broken", "Bicycle or parts of it have been stolen", "Bicycle has been vandalized", "Bicycle has been damaged in a collision with a motor vehicle", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4th checkbox", "Bicycle has been damaged in a collision with a motor vehicle", "Bicycle or parts of it have been stolen", "Bicycle has been vandalized", "Bicycle has got broken", new string[0])]
        public virtual void ClickRadioButtonAndVerify(string version, string radioButton1, string radioButton2, string radioButton3, string radioButton4, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("click radio button and verify", exampleTags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I have opened \"BicycleClaimForm\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.When(string.Format("I click \"{0}\" radio button", radioButton1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.Then(string.Format("\"{0}\" radio button is selected", radioButton1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 11
 testRunner.And(string.Format("\"{0}\" radio button is unselected", radioButton2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And(string.Format("\"{0}\" radio button is unselected", radioButton3), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And(string.Format("\"{0}\" radio button is unselected", radioButton4), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
